CREATE TABLE agentic_missions (
                                  mission_id           VARCHAR(64) PRIMARY KEY,
                                  tenant_id            VARCHAR(128) NOT NULL,
                                  request_id           VARCHAR(128) NOT NULL,
                                  request_fingerprint  VARCHAR(64) NOT NULL,
                                  status               VARCHAR(40) NOT NULL,
                                  selected_path        VARCHAR(32) NOT NULL,
                                  mission_payload      JSONB NOT NULL,
                                  submitted_at         TIMESTAMPTZ NOT NULL,
                                  updated_at           TIMESTAMPTZ NOT NULL,
                                  completed_at         TIMESTAMPTZ,
                                  version              BIGINT NOT NULL DEFAULT 0,

                                  CONSTRAINT uk_agentic_mission_tenant_request
                                      UNIQUE (tenant_id, request_id),
                                  CONSTRAINT uk_agentic_mission_tenant_id
                                      UNIQUE (tenant_id, mission_id),
                                  CONSTRAINT ck_agentic_mission_payload_object
                                      CHECK (jsonb_typeof(mission_payload) = 'object')
);

CREATE INDEX ix_agentic_mission_tenant_status
    ON agentic_missions (tenant_id, status);

CREATE TABLE agentic_checkpoints (
                                     id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     checkpoint_id    VARCHAR(128) NOT NULL,
                                     tenant_id        VARCHAR(128) NOT NULL,
                                     mission_id       VARCHAR(64) NOT NULL,
                                     checkpoint_type  VARCHAR(40) NOT NULL,
                                     schema_version   INTEGER NOT NULL,
                                     content_type     VARCHAR(128) NOT NULL,
                                     sha256           VARCHAR(64) NOT NULL,
                                     size_bytes       BIGINT NOT NULL,
                                     metadata_json    JSONB NOT NULL DEFAULT '{}'::JSONB,
                                     payload          BYTEA NOT NULL,
                                     created_at       TIMESTAMPTZ NOT NULL,

                                     CONSTRAINT uk_agentic_checkpoint_identity
                                         UNIQUE (tenant_id, mission_id, checkpoint_id),
                                     CONSTRAINT fk_agentic_checkpoint_mission
                                         FOREIGN KEY (tenant_id, mission_id)
                                             REFERENCES agentic_missions (tenant_id, mission_id),
                                     CONSTRAINT ck_agentic_checkpoint_schema_version
                                         CHECK (schema_version > 0),
                                     CONSTRAINT ck_agentic_checkpoint_size
                                         CHECK (size_bytes >= 0 AND octet_length(payload) = size_bytes),
                                     CONSTRAINT ck_agentic_checkpoint_metadata_object
                                         CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE INDEX ix_agentic_checkpoint_latest
    ON agentic_checkpoints (
                            tenant_id,
                            mission_id,
                            checkpoint_type,
                            created_at DESC,
                            id DESC
        );

CREATE TABLE agentic_human_gates (
                                     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     gate_id                  VARCHAR(128) NOT NULL,
                                     tenant_id                VARCHAR(128) NOT NULL,
                                     mission_id               VARCHAR(64) NOT NULL,
                                     title                    VARCHAR(300) NOT NULL,
                                     reason                   TEXT NOT NULL,
                                     required_reviewer_roles  JSONB NOT NULL DEFAULT '[]'::JSONB,
                                     review_payload           JSONB NOT NULL DEFAULT '{}'::JSONB,
                                     status                   VARCHAR(32) NOT NULL,
                                     decided_by_user_id       VARCHAR(128) NOT NULL DEFAULT '',
                                     decision_note            TEXT NOT NULL DEFAULT '',
                                     created_at               TIMESTAMPTZ NOT NULL,
                                     expires_at               TIMESTAMPTZ,
                                     decided_at               TIMESTAMPTZ,
                                     version                  BIGINT NOT NULL DEFAULT 0,

                                     CONSTRAINT uk_agentic_gate_identity
                                         UNIQUE (tenant_id, mission_id, gate_id),
                                     CONSTRAINT fk_agentic_gate_mission
                                         FOREIGN KEY (tenant_id, mission_id)
                                             REFERENCES agentic_missions (tenant_id, mission_id),
                                     CONSTRAINT ck_agentic_gate_roles_array
                                         CHECK (jsonb_typeof(required_reviewer_roles) = 'array'),
                                     CONSTRAINT ck_agentic_gate_payload_object
                                         CHECK (jsonb_typeof(review_payload) = 'object')
);

CREATE INDEX ix_agentic_gate_open
    ON agentic_human_gates (tenant_id, mission_id, status, created_at DESC);

CREATE TABLE agentic_runtime_events (
                                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        tenant_id       VARCHAR(128) NOT NULL,
                                        mission_id      VARCHAR(64) NOT NULL,
                                        resume_token    VARCHAR(160) NOT NULL,
                                        mission_status  VARCHAR(40) NOT NULL,
                                        event_payload   JSONB NOT NULL,
                                        emitted_at      TIMESTAMPTZ NOT NULL,

                                        CONSTRAINT uk_agentic_event_resume_token
                                            UNIQUE (tenant_id, mission_id, resume_token),
                                        CONSTRAINT fk_agentic_event_mission
                                            FOREIGN KEY (tenant_id, mission_id)
                                                REFERENCES agentic_missions (tenant_id, mission_id),
                                        CONSTRAINT ck_agentic_event_resume_token
                                            CHECK (btrim(resume_token) <> ''),
                                        CONSTRAINT ck_agentic_event_payload_object
                                            CHECK (jsonb_typeof(event_payload) = 'object')
);

CREATE INDEX ix_agentic_event_replay
    ON agentic_runtime_events (tenant_id, mission_id, id);