syntax = "proto3";

package sparrowx.apigateway.proto.stubs;

option java_package = "com.sparrowx.apigateway.proto.stubs";
option java_multiple_files = true;

service AgenticService {

  rpc Execute(AgenticRequest) returns (AgenticResponse);
}

message AgenticRequest {
  string user_id = 1;
  string prompt = 2;
  //string context = 3;
  // maxTokens = 4;
  //double temperature = 5;
}

message AgenticResponse {
  string output = 1;
  bool success = 2;
  string error = 3;
  //int32 tokensUsed = 4;
}
