spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
#  flyway:
#    schemas: agentic
#    default-schema: agentic
#    create-schemas: true
#    clean-disabled: false
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8085/realms/keycloak-realm/protocol/openid-connect/certs

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
  resource:
    attributes:
      service.name: agentic-service
      service.version: 1.0.0
      service.namespace: sparrowx
      deployment.environment: dev


